aws_region = "ap-southeast-2"
ami_id = "ami-0dfa218cd2f9e8ecd"
instance_type = "t2.micro"
key_name = "amir_sydney"
security_group_name = "xmop-test-sg"
security_group_description = "New sg"
allow_ssh = false
allow_http = false
storage_size_gb = 8
database_type = "mysql"
web_server = "apache2"
